apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhooq-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhooq-springboot
  template:
    metadata:
      labels:
        app: jhooq-springboot
    spec:
      containers:
        - name: springboot
          image: azzu9394/jhooq-springboot-container:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
